version: '2'
services:

#=== OPENLDAP ===
  openldap:
    image: osixia/openldap:1.1.7
    restart: always
    hostname: "ldap.merhylstudio.home"
    environment:
      LDAP_LOG_LEVEL: "stats"
      LDAP_ORGANISATION: "MerhylStudio"
      LDAP_DOMAIN: "merhylstudio.home"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "ldap_search"
      LDAP_READONLY_USER_PASSWORD: "ldap_search"
      LDAP_BACKEND: "hdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - ldap-ldap:/var/lib/ldap
      - ldap-slapd.d:/etc/ldap/slapd.d
      - ldap-certs:/container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "639:639"

#=== PHPLDAPADMIN ===
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    volumes:
      - ldap-phpldapadmin:/var/www/phpldapadmin
    ports:
      - "8001:80"
    links:
      - openldap

#=== VOLUMES ===
volumes:
  ldap:
    driver: local
  slapd.d:
    driver: local
  certs:
    driver: local
  phpldapadmin:
    driver: local
